/*
 * GUI.java
 *
 * Created on __DATE__, __TIME__
 */

package com.zhangminghsuai;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  __USER__
 */
public class GUI extends javax.swing.JFrame {

	/** Creates new form GUI */
	public GUI() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jCheckBox1 = new javax.swing.JCheckBox();
		jCheckBox2 = new javax.swing.JCheckBox();
		jCheckBox3 = new javax.swing.JCheckBox();
		jLabel1 = new javax.swing.JLabel();
		isbn = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		title = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		author = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		pd = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		price = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		countnumber = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		house = new javax.swing.JTextField();
		jLabel10 = new javax.swing.JLabel();
		pr = new javax.swing.JTextField();
		jLabel11 = new javax.swing.JLabel();
		floornumber = new javax.swing.JTextField();
		jLabel12 = new javax.swing.JLabel();
		room = new javax.swing.JTextField();
		ButtonInsert = new javax.swing.JButton();
		jLabel13 = new javax.swing.JLabel();
		Aid = new javax.swing.JTextField();
		jLabel14 = new javax.swing.JLabel();
		Aname = new javax.swing.JTextField();
		jLabel15 = new javax.swing.JLabel();
		Aage = new javax.swing.JTextField();
		jLabel16 = new javax.swing.JLabel();
		Acountry = new javax.swing.JTextField();
		jLabel17 = new javax.swing.JLabel();
		Snumber = new javax.swing.JTextField();
		jLabel18 = new javax.swing.JLabel();
		Sname = new javax.swing.JTextField();
		jLabel19 = new javax.swing.JLabel();
		Saddr = new javax.swing.JTextField();
		jLabel20 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		ButtonUpdate = new javax.swing.JButton();
		jLabel21 = new javax.swing.JLabel();
		Bid = new javax.swing.JTextField();
		jLabel22 = new javax.swing.JLabel();
		Bisdn = new javax.swing.JTextField();
		jLabel23 = new javax.swing.JLabel();
		Bday = new javax.swing.JTextField();
		jLabel24 = new javax.swing.JLabel();
		Bend = new javax.swing.JTextField();
		jLabel25 = new javax.swing.JLabel();
		Bbegin = new javax.swing.JTextField();
		borrow = new javax.swing.JButton();
		ButtonDelete = new javax.swing.JButton();
		jLabel26 = new javax.swing.JLabel();
		Sisbn = new javax.swing.JTextField();
		jLabel27 = new javax.swing.JLabel();
		Sid = new javax.swing.JTextField();
		searchbyISBN = new javax.swing.JButton();
		searchbyS = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		searchAll = new javax.swing.JButton();
		jLabel28 = new javax.swing.JLabel();
		jLabel29 = new javax.swing.JLabel();
		jLabel30 = new javax.swing.JLabel();
		jLabel31 = new javax.swing.JLabel();
		jLabel32 = new javax.swing.JLabel();
		jLabel33 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Library Management System designed by ZhangMingshuai");

		jCheckBox1.setText("\u56fe\u4e66\uff1a");

		jCheckBox2.setText("\u4f5c\u8005\uff1a");

		jCheckBox3.setText("\u5b66\u751f\uff1a");

		jLabel1.setText("ISBN");

		jLabel4.setText("\u4e66\u540d");

		jLabel5.setText("\u4f5c\u8005ID");

		jLabel6.setText("\u51fa\u7248\u65e5\u671f");

		jLabel7.setText("\u4ef7\u683c");

		jLabel8.setText("\u6570\u91cf");

		jLabel9.setText("\u5e93\u623f\u53f7");

		jLabel10.setText("\u51fa\u7248\u793e");

		jLabel11.setText("\u697c\u5c42");

		jLabel12.setText("\u623f\u95f4\u53f7");

		ButtonInsert.setText("\u63d2\u5165");
		ButtonInsert.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ButtonInsertActionPerformed(evt);
			}
		});

		jLabel13.setText("\u4f5c\u8005ID");

		jLabel14.setText("\u59d3\u540d");

		jLabel15.setText("\u5e74\u9f84");

		jLabel16.setText("\u56fd\u5bb6");

		jLabel17.setText("\u5b66\u53f7");

		jLabel18.setText("\u59d3\u540d");

		jLabel19.setText("\u5730\u5740");

		jLabel20.setText("      \u8fd4\u56de\u4fe1\u606f\uff1a");

		ButtonUpdate.setText("\u66f4\u65b0");
		ButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ButtonUpdateActionPerformed(evt);
			}
		});

		jLabel21.setText("\u5b66\u53f7");

		jLabel22.setText("ISBN");

		jLabel23.setText("\u501f\u9605\u65f6\u957f");

		jLabel24.setText("\u5230\u671f\u65e5\u671f");

		jLabel25.setText("\u5f00\u59cb\u65e5\u671f");

		borrow.setText("\u501f\u9605");
		borrow.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				borrowActionPerformed(evt);
			}
		});

		ButtonDelete.setText("\u5220\u9664");
		ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ButtonDeleteActionPerformed(evt);
			}
		});

		jLabel26.setText("ISBN");

		jLabel27.setText("\u5b66\u53f7");

		searchbyISBN.setText("\u67e5\u8be2");
		searchbyISBN.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				searchbyISBNActionPerformed(evt);
			}
		});

		searchbyS.setText("\u67e5\u8be2");
		searchbyS.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				searchbySActionPerformed(evt);
			}
		});

		jScrollPane1.setAutoscrolls(true);

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "ISBN", "书名", "作者名", "作者年龄", "作者国家", "出版商",
						"出版日期", "价格", "库房号", "库存", "房间", "楼层" }));
		jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
		jScrollPane1.setViewportView(jTable1);

		searchAll.setText("\u67e5\u8be2\u5168\u90e8\u56fe\u4e66");
		searchAll.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				searchAllActionPerformed(evt);
			}
		});

		jLabel28.setFont(new java.awt.Font("楷体", 3, 48));
		jLabel28.setText("\u5b66");

		jLabel29.setFont(new java.awt.Font("楷体", 3, 48));
		jLabel29.setText("\u4e60");

		jLabel30.setFont(new java.awt.Font("楷体", 3, 48));
		jLabel30.setText("\u4f7f\u6211\u5feb\u4e50");

		jLabel31.setFont(new java.awt.Font("华文隶书", 2, 24));
		jLabel31.setText("       Study always");

		jLabel32.setFont(new java.awt.Font("华文隶书", 2, 24));
		jLabel32.setText("makes me happy !!!");

		jLabel33.setFont(new java.awt.Font("华文隶书", 2, 24));
		jLabel33.setText("       -Remainin");

		jTable2.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "学号", "姓名", "地址", "图书名", "作者", "借阅开始日期",
						"借阅终止日期" }));
		jScrollPane2.setViewportView(jTable2);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jScrollPane2,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																730,
																Short.MAX_VALUE)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																730,
																Short.MAX_VALUE)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												ButtonInsert,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												99,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												ButtonUpdate,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												93,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												ButtonDelete,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												94,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel20,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												96,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jTextField1,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												134,
																												Short.MAX_VALUE))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								layout
																										.createSequentialGroup()
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																false)
																														.addGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																layout
																																		.createSequentialGroup()
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jLabel25)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				Bbegin,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				119,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jLabel21)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				Bid,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				143,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel24)
																														.addComponent(
																																jLabel22))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																false)
																														.addComponent(
																																Bend,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																84,
																																Short.MAX_VALUE)
																														.addComponent(
																																Bisdn,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																84,
																																Short.MAX_VALUE))
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																false)
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addGap(
																																				11,
																																				11,
																																				11)
																																		.addComponent(
																																				jLabel23)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				Bday,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				0,
																																				Short.MAX_VALUE))
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				borrow,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				219,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)))))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel33,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				139,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				46,
																				46,
																				46))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel26)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				Sisbn,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				193,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				searchbyISBN,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				94,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				13,
																				13,
																				13)
																		.addComponent(
																				jLabel27)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				Sid,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				192,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								searchAll,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								161,
																								Short.MAX_VALUE)
																						.addComponent(
																								searchbyS,
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								161,
																								Short.MAX_VALUE)))
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jCheckBox3)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel17)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												Snumber,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												67,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel18)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												Sname,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												67,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel19)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												Saddr,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												67,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												jLabel31,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												164,
																												Short.MAX_VALUE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								layout
																										.createSequentialGroup()
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jCheckBox1)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jLabel1)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				isbn,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				77,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jLabel4)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				title,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				70,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jLabel5))
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addGroup(
																																				layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING)
																																						.addGroup(
																																								layout
																																										.createSequentialGroup()
																																										.addComponent(
																																												jLabel11)
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																										.addComponent(
																																												floornumber,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												78,
																																												javax.swing.GroupLayout.PREFERRED_SIZE)
																																										.addGap(
																																												41,
																																												41,
																																												41))
																																						.addGroup(
																																								layout
																																										.createSequentialGroup()
																																										.addComponent(
																																												jLabel6)
																																										.addGap(
																																												5,
																																												5,
																																												5)
																																										.addComponent(
																																												pd,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												87,
																																												javax.swing.GroupLayout.PREFERRED_SIZE)
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																										.addComponent(
																																												jLabel7)
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																										.addComponent(
																																												price,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												80,
																																												javax.swing.GroupLayout.PREFERRED_SIZE)
																																										.addPreferredGap(
																																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jLabel8)))
																										.addGap(
																												6,
																												6,
																												6)
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jLabel12)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				room,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				62,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED))
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addGroup(
																																				layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING)
																																						.addComponent(
																																								countnumber,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								65,
																																								Short.MAX_VALUE)
																																						.addComponent(
																																								author,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								65,
																																								Short.MAX_VALUE))
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addGroup(
																																				layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING)
																																						.addComponent(
																																								jLabel9)
																																						.addComponent(
																																								jLabel10))))
																										.addGap(
																												6,
																												6,
																												6)
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																pr,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																101,
																																Short.MAX_VALUE)
																														.addComponent(
																																house,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																101,
																																Short.MAX_VALUE))
																										.addGap(
																												5,
																												5,
																												5)))
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGap(
																												41,
																												41,
																												41)
																										.addComponent(
																												jLabel28)
																										.addGap(
																												28,
																												28,
																												28)
																										.addComponent(
																												jLabel29))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel32,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												187,
																												Short.MAX_VALUE))))
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jCheckBox2)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel13)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				Aid,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				67,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel14)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				Aname,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				67,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel15)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				Aage,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				67,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel16)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				Acountry,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				67,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				11,
																				11,
																				11)
																		.addComponent(
																				jLabel30)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				41,
																				Short.MAX_VALUE)))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jCheckBox1)
																						.addComponent(
																								jLabel1)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								jLabel5)
																						.addComponent(
																								isbn,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								title,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								author,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel10)
																						.addComponent(
																								pr,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																										.addComponent(
																												jLabel7)
																										.addComponent(
																												pd,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(
																												jLabel6)
																										.addComponent(
																												price,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(
																												jLabel8)
																										.addComponent(
																												countnumber,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addComponent(
																								house,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jLabel28)
																		.addComponent(
																				jLabel29)
																		.addComponent(
																				jLabel9)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel30)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																										.addComponent(
																												jLabel11)
																										.addComponent(
																												floornumber,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																										.addComponent(
																												jLabel12)
																										.addComponent(
																												room,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jCheckBox2)
																						.addGroup(
																								layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																										.addComponent(
																												jLabel13)
																										.addComponent(
																												Aid,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(
																												jLabel14)
																										.addComponent(
																												Aname,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(
																												jLabel15)
																										.addComponent(
																												Aage,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(
																												jLabel16)
																										.addComponent(
																												Acountry,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel17)
														.addComponent(
																Snumber,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel18)
														.addComponent(
																Sname,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel19)
														.addComponent(
																Saddr,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jCheckBox3)
														.addComponent(jLabel32)
														.addComponent(jLabel31))
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								ButtonInsert)
																						.addComponent(
																								ButtonUpdate)
																						.addComponent(
																								ButtonDelete)
																						.addComponent(
																								jLabel20)
																						.addComponent(
																								jTextField1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel21)
																						.addComponent(
																								Bid,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel23)
																						.addComponent(
																								jLabel22)
																						.addComponent(
																								Bisdn,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								Bday,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				15,
																				15,
																				15)
																		.addComponent(
																				jLabel33)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel25)
														.addComponent(jLabel24)
														.addComponent(
																Bbegin,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																Bend,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(borrow)
														.addComponent(searchAll))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel26)
														.addComponent(
																Sisbn,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(searchbyS)
														.addComponent(jLabel27)
														.addComponent(
																Sid,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																searchbyISBN))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												130,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												83,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void searchbyISBNActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		jTextField1.setText("");
		DefaultTableModel myModel = (DefaultTableModel) jTable1.getModel();
		myModel.setRowCount(0);
		SearchISBN mys = new SearchISBN(Sisbn.getText());
		jTextField1.setText(mys.goSearch(myModel));
	}

	private void searchbySActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		jTextField1.setText("");
		DefaultTableModel tModel = (DefaultTableModel) jTable2.getModel();
		tModel.setRowCount(0);
		SearchBorrow mySearch = new SearchBorrow(Sid.getText());
		jTextField1.setText(mySearch.goSearch(tModel));
	}

	private void borrowActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		jTextField1.setText("");
		Borrow myBorrow = new Borrow(Bid.getText(), Bisdn.getText(), Bday
				.getText(), Bbegin.getText(), Bend.getText());
		jTextField1.setText(myBorrow.goBorrow());
	}

	private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		jTextField1.setText("");
		if (jCheckBox1.isSelected()) {
			Delete myDelete1 = new Delete();
			jTextField1.setText(myDelete1.goBook(isbn.getText()));
		}
		if (jCheckBox2.isSelected()) {
			Delete myDelete2 = new Delete();
			jTextField1.setText(myDelete2.goAuthor(Aid.getText()));
		}
		if (jCheckBox3.isSelected()) {
			Delete myDelete3 = new Delete();
			jTextField1.setText(myDelete3.goStudent(Snumber.getText()));
		}
	}

	private void ButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		jTextField1.setText("");
		if (jCheckBox1.isSelected()) {
			Update myUpdate1 = new Update(isbn.getText(), title.getText(),
					author.getText(), pr.getText(), pd.getText(), price
							.getText(), house.getText(), countnumber.getText(),
					room.getText(), floornumber.getText());
			jTextField1.setText(myUpdate1.goBook());
		}
		if (jCheckBox2.isSelected()) {
			Update myUpdate2 = new Update(Aid.getText(), Aname.getText(), Aage
					.getText(), Acountry.getText());
			jTextField1.setText(myUpdate2.goAuthor());
		}
		if (jCheckBox3.isSelected()) {
			Update myUpdate3 = new Update(Snumber.getText(), Sname.getText(),
					Saddr.getText());
			jTextField1.setText(myUpdate3.goStudent());
		}
	}

	private void ButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		jTextField1.setText("");
		if (jCheckBox1.isSelected()) {
			Insert myInsert1 = new Insert(isbn.getText(), title.getText(),
					author.getText(), pr.getText(), pd.getText(), price
							.getText(), house.getText(), countnumber.getText(),
					room.getText(), floornumber.getText());
			jTextField1.setText(myInsert1.goBook());
		}
		if (jCheckBox2.isSelected()) {
			Insert myInsert2 = new Insert(Aid.getText(), Aname.getText(), Aage
					.getText(), Acountry.getText());
			jTextField1.setText(myInsert2.goAuthor());
		}
		if (jCheckBox3.isSelected()) {
			Insert myInsert3 = new Insert(Snumber.getText(), Sname.getText(),
					Saddr.getText());
			jTextField1.setText(myInsert3.goStudent());
		}
	}

	private void searchAllActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
		tableModel.setRowCount(0);
		ShowAll myshow = new ShowAll();
		myshow.goShow(tableModel);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GUI().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField Aage;
	private javax.swing.JTextField Acountry;
	private javax.swing.JTextField Aid;
	private javax.swing.JTextField Aname;
	private javax.swing.JTextField Bbegin;
	private javax.swing.JTextField Bday;
	private javax.swing.JTextField Bend;
	private javax.swing.JTextField Bid;
	private javax.swing.JTextField Bisdn;
	private javax.swing.JButton ButtonDelete;
	private javax.swing.JButton ButtonInsert;
	private javax.swing.JButton ButtonUpdate;
	private javax.swing.JTextField Saddr;
	private javax.swing.JTextField Sid;
	private javax.swing.JTextField Sisbn;
	private javax.swing.JTextField Sname;
	private javax.swing.JTextField Snumber;
	private javax.swing.JTextField author;
	private javax.swing.JButton borrow;
	private javax.swing.JTextField countnumber;
	private javax.swing.JTextField floornumber;
	private javax.swing.JTextField house;
	private javax.swing.JTextField isbn;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JCheckBox jCheckBox2;
	private javax.swing.JCheckBox jCheckBox3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JLabel jLabel25;
	private javax.swing.JLabel jLabel26;
	private javax.swing.JLabel jLabel27;
	private javax.swing.JLabel jLabel28;
	private javax.swing.JLabel jLabel29;
	private javax.swing.JLabel jLabel30;
	private javax.swing.JLabel jLabel31;
	private javax.swing.JLabel jLabel32;
	private javax.swing.JLabel jLabel33;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTable1;
	private javax.swing.JTable jTable2;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField pd;
	private javax.swing.JTextField pr;
	private javax.swing.JTextField price;
	private javax.swing.JTextField room;
	private javax.swing.JButton searchAll;
	private javax.swing.JButton searchbyISBN;
	private javax.swing.JButton searchbyS;
	private javax.swing.JTextField title;
	// End of variables declaration//GEN-END:variables

}